version: '3'

services:
  db-volume:
    image: mariadb:10.3
    container_name: db-volume
    volumes:
      - container-volume:/var/lib/mysql
      - ./volume.sql:/docker-entrypoint-initdb.d/volume.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: volume
    restart: always

  phpmyadmin-volume:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-volume
    links:
      - db-volume
    ports:
      - "9002:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: db-volume:3306
    restart: always

  volume-service:
    build: .
    container_name: volume-service
    depends_on:
      - db-volume
    links:
      - db-volume
    external_links:
      - camera-service
      - traffic-streaming-service
#    ports:
#      - "50051:50051"
    environment:
      DB_HOST: "db-volume"
      DB_PORT: "3306"
      DB_NAME: "volume"
      DB_ROOT_PASS: "root"
      CAMERA_HOST: "camera-service"
      CAMERA_PORT: "50052"
    restart: always
    networks:
      - default
      - camera_default
      - trafficstreaming_default

volumes:
  container-volume:

networks:
  camera_default:
    external: true
  trafficstreaming_default:
    external: true