version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: camera
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

  service:
    depends_on:
      - db
    image: volume-of-vehicles:latest
    ports:
      - "50051:50051"
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: root
    
volumes:
  dbdata: