// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: volume.proto
#ifndef GRPC_volume_2eproto__INCLUDED
#define GRPC_volume_2eproto__INCLUDED

#include "volume.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace volume {

class VolumeVehicle final {
 public:
  static constexpr char const* service_full_name() {
    return "volume.VolumeVehicle";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::volume::HelloReply>> SayHello(::grpc::ClientContext* context, const ::volume::HelloRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::volume::HelloReply>>(SayHelloRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::volume::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::volume::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::volume::HelloReply>>(AsyncSayHelloRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::volume::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::volume::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::volume::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientReaderInterface< ::volume::HelloReply>* SayHelloRaw(::grpc::ClientContext* context, const ::volume::HelloRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::volume::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::volume::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::volume::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::volume::HelloRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::volume::HelloReply>> SayHello(::grpc::ClientContext* context, const ::volume::HelloRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::volume::HelloReply>>(SayHelloRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::volume::HelloReply>> AsyncSayHello(::grpc::ClientContext* context, const ::volume::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::volume::HelloReply>>(AsyncSayHelloRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::volume::HelloReply>> PrepareAsyncSayHello(::grpc::ClientContext* context, const ::volume::HelloRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::volume::HelloReply>>(PrepareAsyncSayHelloRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReader< ::volume::HelloReply>* SayHelloRaw(::grpc::ClientContext* context, const ::volume::HelloRequest& request) override;
    ::grpc::ClientAsyncReader< ::volume::HelloReply>* AsyncSayHelloRaw(::grpc::ClientContext* context, const ::volume::HelloRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::volume::HelloReply>* PrepareAsyncSayHelloRaw(::grpc::ClientContext* context, const ::volume::HelloRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHello_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHello(::grpc::ServerContext* context, const ::volume::HelloRequest* request, ::grpc::ServerWriter< ::volume::HelloReply>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SayHello() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* context, const ::volume::HelloRequest* request, ::grpc::ServerWriter< ::volume::HelloReply>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHello(::grpc::ServerContext* context, ::volume::HelloRequest* request, ::grpc::ServerAsyncWriter< ::volume::HelloReply>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHello<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SayHello() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* context, const ::volume::HelloRequest* request, ::grpc::ServerWriter< ::volume::HelloReply>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_SayHello : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithSplitStreamingMethod_SayHello() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler< ::volume::HelloRequest, ::volume::HelloReply>(std::bind(&WithSplitStreamingMethod_SayHello<BaseClass>::StreamedSayHello, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_SayHello() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHello(::grpc::ServerContext* context, const ::volume::HelloRequest* request, ::grpc::ServerWriter< ::volume::HelloReply>* writer) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedSayHello(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::volume::HelloRequest,::volume::HelloReply>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_SayHello<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_SayHello<Service > StreamedService;
};

}  // namespace volume


#endif  // GRPC_volume_2eproto__INCLUDED
